language: go

go:
  - "1.11"

branches:
  only:
    - master

os:
  - linux
  - osx

env:
  - GO111MODULE=on

before_script:
  - [[ "$TRAVIS_OS_NAME" == "linux" ]] && curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - [[ "$TRAVIS_OS_NAME" == "linux" ]] && chmod +x ./cc-test-reporter
  - [[ "$TRAVIS_OS_NAME" == "linux" ]] && ./cc-test-reporter before-build

install:
  - make deps

script:
  - make test

after_script:
  - [[ "$TRAVIS_OS_NAME" == "linux" ]] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
