= Bilocation: a tool for managing files using tags instead of folders

image:https://travis-ci.org/corvus-ch/bilocation.svg?branch=master["Build Status", link="https://travis-ci.org/corvus-ch/bilocation"]
image:https://api.codeclimate.com/v1/badges/31917c2baffbbfa739c3/maintainability["Maintainability", link="https://codeclimate.com/github/corvus-ch/bilocation/maintainability"]
image:https://api.codeclimate.com/v1/badges/31917c2baffbbfa739c3/test_coverage["Test Coverage", link="https://codeclimate.com/github/corvus-ch/bilocation/test_coverage"]
image:https://img.shields.io/badge/deb-packagecloud.io-844fec.svg['DEB Repository, link="https://packagecloud.io/corvus-ch/tools"]
image:https://img.shields.io/badge/rpm-packagecloud.io-844fec.svg['RPM Repository, link="https://packagecloud.io/corvus-ch/tools"]

This file should go into location _A_. But wait, it also belongs to location
_B_. If you face this issue regularly while managing your files, `bilocation`
is for you.

Bilocation puts beside the notion of organizing files in a tree structure and
uses tags instead.

== Installation

=== Install the pre-compiled binary

==== Homebrew

[source,bash]
----
brew install corvus-ch/tools/bilocation
----

==== deb

[source,bash]
----
curl -s https://packagecloud.io/install/repositories/corvus-ch/tools/script.deb.sh | sudo bash
apt install bilocation
----

==== rpm

[source,bash]
----
curl -s https://packagecloud.io/install/repositories/corvus-ch/tools/script.rpm.sh | sudo bash
yum install bilocation
----

=== Compiling from source

[source,bash]
----
git clone git@github.com:corvus-ch/bilocation
cd bilocation
make build
----

== Usage

[source,bash]
----
$ bilocation tag path/to/some/file my_tag
$ bilocation summary
my_tag
$ bilocation search my_tag
path/to/some/file
$ bilocation untag path/to/some/file my_tag
----

See `bilocation help` for all the available commands, options and arguments.

== Contributing and license

This library is licensed under link:LICENSE[MIT]. For information about how to
contribute to this project, see link:CONTRIBUTING.adoc[CONTRIBUTING].
